### ISSUE TITLE
Mirroria Nuc TP not worky

### ISSUE THREAD

**Issue by KalmAndKollected** [fadillzzz/tof-sih#13]
Doesnt let you tp to nucleus in mirroria

**Comment by fadillzzz** [comment]
This might be easy to fix, but right now I only have one account and it's already cleared Mirroria, so I can't test or even reproduce this issue. If anyone's got a dummy account that they're willing to share, please let me know.

**Comment by fadillzzz** [comment]
This should be fixed now.
