### ISSUE TITLE
How to build?

### ISSUE THREAD

**Issue by KalmAndKollected** [fadillzzz/tof-sih#3]
I'm interested in your TOF cheat but they take too long to approve in unknowncheats and I don't know how to build yours since it always gives me an error in vs studio. Could you please help me out? thanks!

**Comment by KalmAndKollected** [comment]
![error](https://github.com/fadillzzz/tof-sih/assets/154399432/bd20246e-df1b-4658-883c-949a1b01d13a)

**Comment by griffith1deady** [comment]
SDK not included. Dump game itself.

**Comment by fadillzzz** [comment]
Use https://github.com/Encryqed/Dumper-7 to get a copy of the SDK and put them in the CppSDK folder.

**Comment by fadillzzz** [comment]
Alternatively, you can also join the Discord server to get an updated version of the hack. https://discord.gg/GhWYwtPH (Check pinned messages)
