### ISSUE TITLE
cant get library error

### ISSUE THREAD

**Issue by newsuzanoebok** [fadillzzz/tof-sih#36]
everytime i press f1 to load on login screen, i got cant get library error
im using the launcher, not steam
game is updated
used the last version of this, but tested others all the same
all with admin privileges
what can i do?

**Comment by fadillzzz** [comment]
Can you provide more details like a screenshot perhaps? Also try closing the launcher and run the injector as non-admin.

**Comment by newsuzanoebok** [comment]
yes use injector as non adm worked lol didnt think xD thx
