### ISSUE TITLE
[Suggestion} Expanding the Quest Tab

### ISSUE THREAD

**Issue by RayshenOmega** [fadillzzz/tof-sih#53]
1. Complete all quests having a check box to exclude story quests
2. Moving Crew mission quests to have its own button for weeklies
3. Mentor missions have its own button for weeklies.
4. Quest buttons to be Horizontal instead of Vertical.
5.

**Comment by Dynamixus** [comment]
+1 for point number 1 please

**Comment by fadillzzz** [comment]
These changes have been implemented with the exception of number 3 which I'll revisit some other time.

**Comment by fadillzzz** [comment]
Number 3 has been addressed via #66
