### ISSUE TITLE
{Issue}Complete main quest(s)

### ISSUE THREAD

**Issue by noneh1** [fadillzzz/tof-sih#64]
Complete main quest(s) not working for me, complete all quests works perfectly i don't know why

**Comment by fadillzzz** [comment]
Is this a brand new character and/or still in the tutorial/intro missions?

**Comment by noneh1** [comment]
Yes, brand new account

**Comment by fadillzzz** [comment]
Yeah it's a known issue. Low priority though. You can keep using Complete All Quests until eventually you're out of the intro missions and you'll be part of the "main quests"

**Comment by noneh1** [comment]
I see, no problem then just wanted to know, tyvm for your work and fast answer!
