### ISSUE TITLE
"Please start the game from Steam" when launching the injector.

### ISSUE THREAD

**Issue by Dynamixus** [fadillzzz/tof-sih#67]
Hey, I finally had the time to check out the update but i'm getting this:

![XGWoEqDFyIo6Ff](https://github.com/fadillzzz/tof-sih/assets/137287047/e4402308-b90a-4d5b-a6fd-b938f298c211)

tried running it through steam and then launching the injector but yeah that didn't work
the runasinvoker step also didn't work btw

![image](https://github.com/fadillzzz/tof-sih/assets/137287047/a721c73f-1a93-452b-8439-97035b0761de)

this guy said that maybe this will work, if that helps. thank you very much again for taking the time to make a steam build T_T

**Comment by fadillzzz** [comment]
The current implementation of the injector is rather naive and makes the assumption that you're using the official launcher version. To inject the DLL into the Steam version of the game, for now, I recommend using a third party injector such as GH Injector or Extreme Injector and have it auto inject the DLL using manual mapping w/ thread hijacking.
