### ISSUE TITLE
last version not working

### ISSUE THREAD

**Issue by newsuzanoebok** [fadillzzz/tof-sih#70]
the game closes itself right when it get launched
![Screenshot_2](https://github.com/fadillzzz/tof-sih/assets/153226193/94aea1aa-6329-4282-b3e9-612eae4baf0a)
those are the messages at the injector.exe

that 'launcher is already running' message at the top appears even if there is no launcher, even if i restart pc and try right away with nothing opened
sometimes this message dont appear and even then game closes itself right away

edit: the version [Infinite dodges (#68)] works fine

**Comment by fadillzzz** [comment]
Injector is kinda in a broken state right now. I'll have to recreate it in the future. In the meantime, please use a third party injector such as Extreme Injector or GH Injector.
