### ISSUE TITLE
Version Adaptation CN

### ISSUE THREAD

**Issue by XIAYI1314** [fadillzzz/tof-sih#72]
Failed, can't complete the cn version of the sdk in advance, I want to request an adapted cn version, I think I can provide an account and client, of course this is just a request, not a job

**Comment by fadillzzz** [comment]
DM me the details, and I'll see what I can do

**Comment by fadillzzz** [comment]
A CN build is available at https://github.com/fadillzzz/tof-sih/releases/tag/1.4.11
