### ISSUE TITLE
Not opening 

### ISSUE THREAD

**Issue by Hydr0xygenZ** [fadillzzz/tof-sih#79]
Injects fine but when i load into the game and press insert for some reason nothing happens. And i'm using dx12
![123](https://github.com/fadillzzz/tof-sih/assets/169789570/f9d51410-feaa-4045-9161-c0280b15f2d0)

**Comment by fadillzzz** [comment]
Do you perhaps have any overlays running?

**Comment by Hydr0xygenZ** [comment]
Only rivatuner and maybe the xbox game bar, can any of them be affecting?

**Comment by fadillzzz** [comment]
Yes, please try disabling them.

**Comment by Hydr0xygenZ** [comment]
Well i tried with rivatuner closed and yeah that was it. Thanks!
