### ISSUE TITLE
Failed to inject

### ISSUE THREAD

**Issue by momosensei000** [fadillzzz/tof-sih#80]
Launcher is already running.
If it wasn't started by this injector. Please close it and launch the injector again.
Injection method: manual
Launcher has been started. Please start the game from the launcher.
Injecting C:\Users\muham\Downloads\TOFInternal-official (1)\TOFInternal.dll
File ok
Target process memory allocation failed (ex) 0x6
Failed to inject.

**Comment by fadillzzz** [comment]
Is this happening consistently? Can you confirm that you let the injector start the launcher? Did you run the injector as admin?

**Comment by RayshenOmega** [comment]
Injector has been overhaled some time ago closing this issue
