### ISSUE TITLE
The Complete Quest is not working

### ISSUE THREAD

**Issue by yamato206** [fadillzzz/tof-sih#85]
From Quest tab Complete Quest is not working on version 1.5 for game version 4.1.1, i know that the codebase is for game version 4.1.0, just letting you know and also cutom GUI is not working

**Comment by RayshenOmega** [comment]
> From Quest tab Complete Quest is not working on version 1.5 for game version 4.1.1, i know that the codebase is for game version 4.1.0, just letting you know and also cutom GUI is not working

Just got home from work and decided to test this to see if there was a issue. I can report quests is working with 4.1.1 version. The only thing i cant test is mentor missions quests but thats not important since it uses the same calls
